### ISSUE TITLE
EMail registration stopped working

### ISSUE THREAD

**Issue by JoshWho** [chsaiujwal/miab_registration_page#1]
Has there been any changes updates that might have broke this?

you can test out at https://2me.ltd

**Comment by chsaiujwal** [comment]
you sure its not working? because i just created a new mail 1234321@2me.ltd and its working...

**Comment by JoshWho** [comment]
That is awesome. Maybe it must have been my browser messing up with cookies. Thank you for checking it.

**Comment by chsaiujwal** [comment]
welcome
