### ISSUE TITLE
Error hcaptcha

### ISSUE THREAD

**Issue by ycosteri** [chsaiujwal/miab_registration_page#2]
Hi I read your readme and ran the installer.

I always get the usual error

"incorrect captcha, please go back to login page and try again! :-("

the url is this: https://mailbox.flamehost.it/register.html

the domain is mailbox.flamehost.it
if I enter for example test@mailbox.flamehost.it and generate a random password, I answer the question cel captcha but I always get the error "incorrect captcha, please go back to login page and try again! :-("

can you help me?

Sorry for my bad english

Ygor

**Comment by chsaiujwal** [comment]
hey, i am really sorry for coming online and replying after many weeks. did you add a valid hcaptcha token and edit this line https://github.com/chsaiujwal/miab_registration_page/blob/main/register.html#L214 ?
